export const jobTitles: string[] = [
    'Software Engineer',
    'Data Analyst',
    'Product Manager',
    'UX/UI Designer',
    'Event Planner',
    'Logistics Coordinator',
    'Supply Chain Manager',
    'Healthcare Administrator',
    'Registered Nurse',
    'Pharmacist',
    'Musician',
    'Actor',
    'Artist',
    'Writer',
    'Photographer',
    'Model',
    'Dancer',
    'Athlete',
    'Coach',
    'Fitness Instructor',
    'Singer',
    'Guitarist',
    'Pianist',
    'Violinist',
    'Flutist',
    'Drummer',
    'Bassist',
    'Physical Therapist',
    'Lawyer',
    'Teacher',
    'Research Scientist',
    'Psychologist',
    'Veterinarian',
    'Dentist',
    'Police Officer',
    'Firefighter',
    'Chef',
    'Baker',
    'Barista',
    'Bartender',
    'Waiter',
    'Cashier',
    'Hotel Manager',
    'Marketing Manager',
    'Sales Representative',
    'Financial Analyst',
    'HR Manager',
    'Operations Manager',
    'Project Manager',
    'Business Analyst',
    'Account Manager',
    'Graphic Designer',
    'Content Writer',
    'Customer Service Representative',
    'IT Support Specialist',
    'Web Developer',
    'Quality Assurance Analyst',
    'Digital Marketing Specialist',
    'Social Media Manager',
    'Network Administrator',
    'Systems Administrator',
    'Data Scientist',
    'Artificial Intelligence Engineer',
    'Cybersecurity Analyst',
    'Product Owner',
    'DevOps Engineer',
    'Technical Writer',
    'Business Development Manager',
    'UI/UX Developer',
    'Civil Engineer',
    'Architect',
    'Mechanical Engineer',
    'Electrical Engineer',
    'Chemical Engineer',
    'Accountant',
    'Financial Advisor',
    'Human Resources Coordinator',
    'Operations Analyst',
    'Project Coordinator',
    'Business Consultant',
]
