export const universities: string[] = [
    'Vietnam National University, Hanoi',
    'Vietnam National University, Ho Chi Minh City',
    'Hanoi University of Science and Technology',
    'Ho Chi Minh City University of Technology',
    'University of Economics and Business, Vietnam National University, Hanoi',
    'Foreign Trade University',
    'Hanoi Medical University',
    'Ho Chi Minh City Medicine and Pharmacy University',
    'Hue University',
    'Vietnam National University of Agriculture',
    'Hanoi University of Agriculture',
    'Hanoi Pedagogical University',
    'Vietnam National University of Forestry',
    'Vietnam National University of Fine Arts',
    'Ho Chi Minh City University of Education',
    'University of Languages and International Studies, Vietnam National University, Hanoi',
    'Hanoi University of Mining and Geology',
    'University of Transport and Communications, Vietnam',
    'Vietnam National University of Social Sciences and Humanities',
    'Can Tho University',
    'Danang University of Economics',
    'University of Da Lat',
    'Ho Chi Minh City University of Foreign Languages and Information Technology',
    'Vietnam Maritime University',
    'Nha Trang University',
    'University of Information Technology, Vietnam National University, Hanoi',
    'University of Natural Sciences, Vietnam National University, Ho Chi Minh City',
    'Vietnam National University of Arts Education',
    'Vietnam National University of Theater and Cinema',
    'Danang University of Technology',
    'Hanoi University of Business and Technology',
    'Hanoi Open University',
    'Ho Chi Minh City University of Architecture',
    'Hanoi University',
    'Vietnam National University of Music and Dance',
    'Ho Chi Minh City University of Fine Arts',
    'University of Social Sciences and Humanities, Vietnam National University, Ho Chi Minh City',
    'Hanoi University of Technology and Education',
    'Hanoi University of Civil Engineering',
    'Hanoi University of Industry',
    'University of Medicine and Pharmacy, Vietnam National University, Hanoi',
    'Thai Nguyen University',
    'Vietnam National University of Sports',
    'University of Finance and Marketing',
    'Dong Nai University',
    'Ba Ria - Vung Tau University',
    'Vietnam National University of Agriculture, South Campus',
    'Vinh University',
    'Thai Nguyen University of Social Sciences and Humanities',
    'Vietnam National University of Art Education',
    'University of Technical Education Ho Chi Minh City',
    'Vietnam National University of Forestry and Agriculture',
    'Hoa Sen University',
    'Can Tho University of Medicine and Pharmacy',
    'University of Water Resources',
    'Vietnam National University of Civil Engineering',
    'Quy Nhon University',
    'Hai Phong University',
    'Hanoi University of Pharmacy',
    'Dong Thap University',
    'University of Technology and Education, Thai Nguyen University',
    'Hanoi National University of Education',
    'Ton Duc Thang University',
    'Bac Lieu University',
    'Hong Bang International University',
    'Ho Chi Minh City University of Technology and Education',
    'Hanoi Law University',
    'Vietnam National University of Music',
    'Hanoi University of Natural Resources and Environment',
    'Hanoi University of Culture',
    'Hue University of Agriculture and Forestry',
    'Ho Chi Minh City University of Law',
    'Thai Nguyen University of Agriculture and Forestry',
    'Vinh Long University of Technology Education',
    'Ho Chi Minh City University of Information Technology',
    'Hanoi University of Physical Education and Sports',
    'Hung Yen University of Technology and Education',
    'University of Dalat - Lam Dong Campus',
    'Hanoi Architectural University',
    'Hanoi National Economics University',
    'Thai Nguyen University of Information and Communication Technology',
    'Ho Chi Minh City Open University',
    'Hanoi College of Pharmacy',
    'Hue University of Medicine and Pharmacy',
    'University of Education, Hue University',
    'University of Industrial Fine Arts, Ho Chi Minh City',
    'Can Tho University of Technology',
    'VNU University of Science',
    'Hanoi University of Science',
    'Vietnam National University of Agriculture, Central Campus',
    'Dai Nam University',
    'Pham Ngoc Thach University of Medicine',
    'Hanoi University of Natural Sciences',
    'University of Science, Hue University',
    'Bac Ninh University of Sport and Physical Education',
    'Hanoi University of Home Affairs',
    'Can Tho University of Technology and Education',
    'Danang University of Foreign Language Studies',
    'Danang University of Education',
    'Hanoi Architectural University - Bac Ninh Campus',
    'Hanoi Industrial Textile Garment University',
    'Hanoi National University of Civil Engineering',
    'Vietnam National University of Agriculture, Southwest Campus',
    'Hai Duong University of Agriculture and Forestry',
    'Hue University of Sciences',
    'Ho Chi Minh City University of Technical Education',
    'Hanoi University of Industry - Hai Phong Campus',
    'Vietnam Academy of Music',
    'Hanoi Law University - Ho Chi Minh City Campus',
    'Hanoi University of Business and Management',
    'Quang Binh University',
    'Bac Kan University',
    'Ho Chi Minh City University of Culture',
    'Ho Chi Minh City University of Food Industry',
    'Bac Lieu University - Ca Mau Campus',
    'Hanoi Pedagogical University No. 2',
    'Hanoi College of Science and Technology',
    'Hanoi National University of Physical Education and Sports',
    'Ho Chi Minh City University of Pedagogy',
    'Vinh University of Technology Education',
]
